import 'package:cumbialive/model/models.dart';

// Este es el user que se usa en toda la aplicación.
// No tocarlo ni moverlo de acá.

User user = User();

String defaultCountry = "Colombia";

class Constants {
  static List listOfCountries = [
    {"country_code": "AD", "country_name": "ANDORRA"},
    {"country_code": "AD", "country_name": "ANDORRA"},
    {"country_code": "DZ", "country_name": "ALGERIA"},
    {"country_code": "AM", "country_name": "ARMENIA"},
    {"country_code": "AR", "country_name": "ARGENTINA"},
    {"country_code": "AS", "country_name": "AMERICAN"},
    {"country_code": "AT", "country_name": "AUSTRIA"},
    {"country_code": "AU", "country_name": "AUSTRALIA"},
    {"country_code": "AZ", "country_name": "AZERBAIJAN"},
    {"country_code": "AZ", "country_name": "AZERBAIJAN"},
    {"country_code": "BA", "country_name": "BOSNIA AND HERZEGOVINA"},
    {"country_code": "BD", "country_name": "BANGLADESH"},
    {"country_code": "BE", "country_name": "BELGIUM"},
    {"country_code": "BG", "country_name": "BULGARIA"},
    {"country_code": "BN", "country_name": "BRUNEI"},
    {"country_code": "BR", "country_name": "BRAZIL"},
    {"country_code": "BR", "country_name": "BRAZIL"},
    {"country_code": "BR", "country_name": "BRAZIL"},
    {"country_code": "BY", "country_name": "BELARUS"},
    {"country_code": "CA", "country_name": "CANADA"},
    {"country_code": "CA", "country_name": "CANADA"},
    {"country_code": "CN", "country_name": "CHINA, PEOPLES REPUBLIC"},
    {"country_code": "CO", "country_name": "COLOMBIA"},
    {"country_code": "CU", "country_name": "CUBA"},
    {"country_code": "CY", "country_name": "CYPRUS"},
    {"country_code": "HR", "country_name": "CROATIA"},
    {"country_code": "CZ", "country_name": "CZECH REPUBLIC, THE"},
    {"country_code": "DE", "country_name": "GERMANY"},
    {"country_code": "DK", "country_name": "DENMARK"},
    {"country_code": "EC", "country_name": "ECUADOR"},
    {"country_code": "EE", "country_name": "ESTONIA"},
    {"country_code": "ES", "country_name": "SPAIN"},
    {"country_code": "FI", "country_name": "FINLAND"},
    {"country_code": "FM", "country_name": "MICRONESIA, FEDERATED STATES OF"},
    {"country_code": "FO", "country_name": "FAROE ISLANDS"},
    {"country_code": "FR", "country_name": "FRANCE"},
    {"country_code": "GE", "country_name": "GEORGIA"},
    {"country_code": "GF", "country_name": "FRENCH GUYANA"},
    {"country_code": "GG", "country_name": "GUERNSEY"},
    {"country_code": "GL", "country_name": "GREENLAND"},
    {"country_code": "GP", "country_name": "GUADELOUPE"},
    {"country_code": "GR", "country_name": "GREECE"},
    {"country_code": "GU", "country_name": "GUAM"},
    {"country_code": "HU", "country_name": "HUNGARY"},
    {"country_code": "IC", "country_name": "CANARY ISLANDS, THE"},
    {"country_code": "ID", "country_name": "INDONESIA"},
    {"country_code": "IL", "country_name": "ISRAEL"},
    {"country_code": "IN", "country_name": "INDIA"},
    {"country_code": "IS", "country_name": "ICELAND"},
    {"country_code": "IT", "country_name": "ITALY"},
    {"country_code": "JE", "country_name": "JERSEY"},
    {"country_code": "JP", "country_name": "JAPAN"},
    {"country_code": "KG", "country_name": "KYRGYZSTAN"},
    {"country_code": "KH", "country_name": "CAMBODIA"},
    {"country_code": "KR", "country_name": "KOREA, REPUBLIC OF (SOUTH K.)"},
    {"country_code": "KV", "country_name": "KOSOVO"},
    {"country_code": "KZ", "country_name": "KAZAKHSTAN"},
    {"country_code": "LI", "country_name": "LIECHTENSTEIN"},
    {"country_code": "LT", "country_name": "LITHUANIA"},
    {"country_code": "LU", "country_name": "LUXEMBOURG"},
    {"country_code": "LV", "country_name": "LATVIA"},
    {"country_code": "MA", "country_name": "MOROCCO"},
    {"country_code": "MC", "country_name": "MONACO"},
    {"country_code": "MD", "country_name": "MOLDOVA, REPUBLIC OF"},
    {"country_code": "ME", "country_name": "MONTENEGRO, REPUBLIC OF"},
    {"country_code": "MG", "country_name": "MADAGASCAR"},
    {"country_code": "MH", "country_name": "MARSHALL ISLANDS"},
    {"country_code": "MK", "country_name": "MACEDONIA, REPUBLIC OF"},
    {"country_code": "MN", "country_name": "MONGOLIA"},
    {"country_code": "MN", "country_name": "MONGOLIA"},
    {"country_code": "MP", "country_name": "COMMONWEALTH NO. MARIANA ISLANDS"},
    {"country_code": "MQ", "country_name": "MARTINIQUE"},
    {"country_code": "MV", "country_name": "MALDIVES"},
    {"country_code": "MX", "country_name": "MEXICO"},
    {"country_code": "MY", "country_name": "MALAYSIA"},
    {"country_code": "YT", "country_name": "MAYOTTE"},
    {"country_code": "NC", "country_name": "NEW CALEDONIA"},
    {"country_code": "NL", "country_name": "NETHERLANDS, THE"},
    {"country_code": "NO", "country_name": "NORWAY"},
    {"country_code": "NZ", "country_name": "NEW ZEALAND"},
    {"country_code": "PG", "country_name": "PAPUA NEW GUINEA"},
    {"country_code": "PH", "country_name": "PHILIPPINES, THE"},
    {"country_code": "PK", "country_name": "PAKISTAN"},
    {"country_code": "PL", "country_name": "POLAND"},
    {"country_code": "PR", "country_name": "PUERTO RICO"},
    {"country_code": "PT", "country_name": "PORTUGAL"},
    {"country_code": "PW", "country_name": "PALAU"},
    {"country_code": "RE", "country_name": "REUNION, ISLAND OF"},
    {"country_code": "RO", "country_name": "ROMANIA"},
    {"country_code": "RS", "country_name": "SERBIA, REPUBLIC OF"},
    {"country_code": "RU", "country_name": "RUSSIAN FEDERATION, THE"},
    {"country_code": "SE", "country_name": "SWEDEN"},
    {"country_code": "CH", "country_name": "SWITZERLAND"},
    {"country_code": "SG", "country_name": "SINGAPORE"},
    {"country_code": "SH", "country_name": "SAINT HELENA"},
    {"country_code": "SI", "country_name": "SLOVENIA"},
    {"country_code": "SK", "country_name": "SLOVAKIA"},
    {"country_code": "SM", "country_name": "SAN MARINO"},
    {"country_code": "XY", "country_name": "ST. BARTHELEMY"},
    {"country_code": "ZA", "country_name": "SOUTH AFRICA"},
    {"country_code": "SZ", "country_name": "SWAZILAND"},
    {"country_code": "TH", "country_name": "THAILAND"},
    {"country_code": "TN", "country_name": "TUNISIA"},
    {"country_code": "TR", "country_name": "TURKEY"},
    {"country_code": "TW", "country_name": "TAIWAN"},
    {"country_code": "TW", "country_name": "TAIWAN"},
    {"country_code": "UA", "country_name": "UKRAINE"},
    {"country_code": "GB", "country_name": "UNITED KINGDOM"},
    {"country_code": "US", "country_name": "UNITED STATES OF AMERICA"},
    {"country_code": "UZ", "country_name": "UZBEKISTAN"},
    {"country_code": "VI", "country_name": "VIRGIN ISLANDS (US)"}

  ];
}
